//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minina0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Materials_in_products = new HashSet<Materials_in_products>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Units_cost { get; set; }
        public Nullable<int> Count_in_stock { get; set; }
        public Nullable<int> ID_Material_Type { get; set; }
    
        public virtual Material_type Material_type { get; set; }
        public virtual ICollection<Materials_in_products> Materials_in_products { get; set; }
    }
}
