//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minina0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type
    {
        public Material_type()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int ID { get; set; }
        public string Material_type_name { get; set; }
        public Nullable<double> Percentage_of_defective_materials { get; set; }
    
        public virtual ICollection<Material> Material { get; set; }
    }
}
