//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minina0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials_in_products
    {
        public int ID { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> ID_Material { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Products Products { get; set; }
    }
}
