//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minina0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Materials_in_products = new HashSet<Materials_in_products>();
            this.Partner_products_request = new HashSet<Partner_products_request>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Product_type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Article { get; set; }
        public Nullable<double> Minimal_cost_for_partner { get; set; }
    
        public virtual ICollection<Materials_in_products> Materials_in_products { get; set; }
        public virtual ICollection<Partner_products_request> Partner_products_request { get; set; }
        public virtual Product_type Product_type { get; set; }
    }
}
