//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minina0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_type
    {
        public Product_type()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ID { get; set; }
        public string Product_type_name { get; set; }
        public Nullable<double> Product_Type_Factor { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
